#ifndef SHINO_REPLAY_H
#define SHINO_REPLAY_H

#include <cstdint>
#include <istream>
#include <string>

namespace shino {

struct ReplaySummary {
  std::uint64_t events = 0;
  std::uint64_t reads = 0;
  std::uint64_t writes = 0;
  std::uint64_t first_time_ns = 0;
  std::uint64_t last_time_ns = 0;
};

// Validates and summarizes JSONL generated by TraceWriter. This deliberately
// replays the timing/event stream only; SystemC remains the functional oracle.
ReplaySummary replay_trace(std::istream& input);

}  // namespace shino

#endif  // SHINO_REPLAY_H
